import { writeFile } from "node:fs/promises";
import { ROUTES } from "../src/route-manifest.ts";

const outputPath = new URL("../cmd/octopool/routes_generated.go", import.meta.url);
const seenPatterns = new Set();
const patterns = ROUTES.map((route) => {
  if (seenPatterns.has(route.pattern.source)) {
    throw new Error(`Duplicate route pattern: ${route.pattern.source}`);
  }
  seenPatterns.add(route.pattern.source);
  const pattern = route.pattern.source.replaceAll("\\/", "/").replaceAll(/\(\?<[^>]+>/g, "(?:");
  if (pattern.includes("`")) {
    throw new Error(`Route pattern cannot contain a backtick: ${pattern}`);
  }
  return pattern;
});

const lines = [
  "// Code generated by scripts/generate-routes.mjs from src/route-manifest.ts; DO NOT EDIT.",
  "",
  "package main",
  "",
  'import "regexp"',
  "",
  "var relayQueryPathPatterns = []*regexp.Regexp{",
  ...patterns.map((pattern) => `\tregexp.MustCompile(\`${pattern}\`),`),
  "}",
  "",
];

await writeFile(outputPath, lines.join("\n"));
